### ISSUE TITLE
Tienes algun pantallazo?

### ISSUE THREAD

**Issue by johnfelipe** [kplian/sis_tesoreria#1]

**Comment by rensi4rn** [comment]
![image](https://cloud.githubusercontent.com/assets/2071383/11300127/cd02f8c2-8f62-11e5-827f-f18f99bb7a92.png)


![image](https://cloud.githubusercontent.com/assets/2071383/11300141/f33002ba-8f62-11e5-84f1-ec9f8246faf5.png)


![image](https://cloud.githubusercontent.com/assets/2071383/11300155/241fabbe-8f63-11e5-97c5-bc4a5fc91ead.png)

**Comment by johnfelipe** [comment]
Se puede modificar para la contabilidad colombiana?

**Comment by rensi4rn** [comment]
Yo creo que si, es un sistema grande.
te mande una invitación al foro allá te podemos ayudar
