### ISSUE TITLE
BUG, la solicitud de efectivo me permitio sobregirar la capacidad de caja

### ISSUE THREAD

**Issue by rensi4rn** [kplian/sis_tesoreria#12]
cree una caja con capacidad de 5000 BS y solicite en efectivo de la caja 5001,
se necesario agregar validaciones que consideren otros retiros y el saldo efectivo de caja.

![image](https://cloud.githubusercontent.com/assets/2071383/14365281/d2759086-fcda-11e5-84a1-ec0415877779.png)

**Comment by GonzaloSarmientoS** [comment]
Solucionado
