### ISSUE TITLE
Listado de funcionarios solicitantes

### ISSUE THREAD

**Issue by grovervelasquez** [kplian/sis_tesoreria#15]
Al listar los funcionarios que pueden solicitar efectivo, lista todos cargos por los que paso un funcionario.

Tendria que listar solo el cargo en el que esta activo, lo mismo sucede al listar funcionarios en la pantalla para asignar cajeros.

![image](https://cloud.githubusercontent.com/assets/18399403/14439255/40a02c9a-fff8-11e5-9dc9-548ea6709946.png)

**Comment by GonzaloSarmientoS** [comment]
Solucionado
