### ISSUE TITLE
rendición sobregirada de solicitante de caja

### ISSUE THREAD

**Issue by rensi4rn** [kplian/sis_tesoreria#2]
la rendir me permitió registras dos facturas que sobregiraban, en la primera coloque devolver el saldo, y la segunda quedo colgada al querer pasar al siguiente estado da un error de estados.

Posible solucion (antes finalizar una solicitud verificar si tiene otras facturas en proceso)

**Comment by rensi4rn** [comment]
Mejor solución aun,   no permitir registrar otra rendición si existe una en proceso

**Comment by GonzaloSarmientoS** [comment]
Se implemento que no pueda registrar otro proceso mientras exista otro pendiente.
Resuelto
