### ISSUE TITLE
BUG, Las rendiciones tiene que considerar el liquido pagable

### ISSUE THREAD

**Issue by rensi4rn** [kplian/sis_tesoreria#9]
Al  hacer rendiciones de solicitante y de caja se tiene que considerar el monto liquido pagado de los documentos

**Comment by GonzaloSarmientoS** [comment]
Tanto en las rendiciones efectivo de solicitante como en las rendiciones de caja se toma el monto liquido pagable, no encontre el bug

**Comment by rensi4rn** [comment]
Esto es lo que hice: tenía de saldo 300, registre una factura de 100 y un recibo con retención de servicio por 200,  debería calcular que la retención se devuelve  al cajero pero no lo hace

**Comment by GonzaloSarmientoS** [comment]
Solucionado
